### ISSUE TITLE
axios kütüphanesi hk.

### ISSUE THREAD

**Issue by aligundogdu** [ademilter/vakitler#5]
Adem selam,
projede axios kullanmanın özel bir nedeni var mı ? yoksa tamamen alışkanlık ile ilgili mi ?

teşekkürler.

**Comment by ademilter** [comment]
alışkanlık diyelim abi. trayıcı uyumluluğu endişesi taşıyan projelerde kullana kullana olmazsa olmazlarımdan olmuş biraz :). `fetch` (ie hariç) bütün tarayıcılarda çalışıyor aslında, bi kaç kişi daha aynı yere takıldı. hemen update çıkalım rahatlayalım :)

**Comment by aligundogdu** [comment]
Alışkanlık olduğunu tahmin etmiştim. Ben vue resource kullanıyorum , axios un ekstra avantajı var mı merak etmiştim. Bu sayede kütüphanenin varlığından haberim oldu teşekkürler :+1:
